[project]
name = "weber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bleak>=0.22.3",
    "pydantic>=2.11.4",
    "pytest>=8.3.5",
    "telegram>=0.0.1",
]
